TP3BanqueAdamEme/TP3BanqueAdamEme-war/src/java/managed/CompteBancaireMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managed;

import entity.Client;
import entity.CompteBancaire;
import entity.Operation;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import session.GestionnaireDeCompteBancaire;
import session.GestionnairePersonne;

/**
 *
 * @author issoufiadam
 */
@Named(value = "compteBancaireMBean")
@SessionScoped
public class CompteBancaireMBean implements Serializable{
   
    @EJB
    private GestionnaireDeCompteBancaire gestionnaireDeCompteBancaire;
    @EJB
    private GestionnairePersonne gestionnairePersonne;
    
    private List<CompteBancaire> comptes = new ArrayList<CompteBancaire>();
    private CompteBancaire compteCourant = null;
    
    // attribut utilisé lors de la création de compte
    private String type;
    private Client client;
    private Long clientId;
    private int montant = 0;
    
    /**
     * Creates a new instance of ListCompteBancaireMBean
     */
    public CompteBancaireMBean() {
        // gestionnaireDeCompteBancaire.creerComptesTest();
    }
    
    public void creerCompteBancaireTest() {
        gestionnaireDeCompteBancaire.creerComptesTest();
    } 
    
    public List<CompteBancaire> getAllComptes() {
        return gestionnaireDeCompteBancaire.getAllComptes();
    }
    
    public Collection<Operation> getAllOperations() {
        if (compteCourant == null) return null;
        return compteCourant.getOperations();
    }
    
    public List<String> getTypes() {
        return gestionnaireDeCompteBancaire.getTypes();
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(String clientId) {
        this.client = gestionnairePersonne.getClient(Long.parseLong(clientId, 10));
    }

    public int getMontant() {
        return montant;
    }

    public void setMontant(int montant) {
        this.montant = montant;
    }
    
    public void creerCompte(CompteBancaire c) {
        gestionnaireDeCompteBancaire.creerCompte(c);
    }
    
    public CompteBancaire getCompte(Long compteBancaireId) {
        return gestionnaireDeCompteBancaire.getCompte(compteBancaireId);
    }
    
    public CompteBancaire getCompteCourant() {
        return compteCourant;
    }
    
    public String getNom() {
        return (compteCourant == null) ? "Undefined" : compteCourant.getNom();
    }
    
    public String getSolde() {
        return (compteCourant == null) ? "Undefined" : "" + compteCourant.getSolde();
    }
    
    public void setCompteCourant(Long compteBancaireId) {
        System.out.println("Compte courant : " + compteBancaireId);
        compteCourant = gestionnaireDeCompteBancaire.getCompte(compteBancaireId);
    }

    public Long getClientId() {
        return clientId;
    }

    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }
    

    // Les actions string
    public String actionStringCreer(String url) {
        System.out.println("managed.CompteBancaireMBean.actionStringCreer()");
        if (clientId == null || type == null) return url + "?faces-redirect=true";
        this.client = gestionnairePersonne.getClient(clientId);
        gestionnaireDeCompteBancaire.creerCompte(type, montant, client);
        reset();
        return url + "?faces-redirect=true";
    }
    
    public String actionStringSupprimer(Long compteBancaireId, String url) {
        gestionnaireDeCompteBancaire.supprimer(compteBancaireId);
        return url + "?faces-redirect=true";
    }
    
    public String actionStringConsulter(Long compteBancaireId, String url) {
        compteCourant = gestionnaireDeCompteBancaire.getCompte(compteBancaireId);
        return url + "?faces-redirect=true";
    }
    
    // Other
    public void reset() {
        clientId = null;
        type = null;
        montant = 0;
    }
}

TP3BanqueAdamEme/TP3BanqueAdamEme-war/src/java/managed/PersonneMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managed;

import entity.Administrateur;
import entity.Client;
import entity.Conseiller;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import session.GestionnairePersonne;

/**
 *
 * @author issoufiadam
 */
@Named(value = "personneMBean")
@SessionScoped
public class PersonneMBean implements Serializable {

    @EJB
    private GestionnairePersonne gestionnairePersonne;
    
    String nom;
    String prenom;
    String adresse;
    Conseiller conseiller;
    
    /**
     * Creates a new instance of PersonneMBean
     */
    public PersonneMBean() {
    }
    
    //
    public List<Client> getAllClients() {
        return gestionnairePersonne.getAllClients();
    }
    
    public List<Conseiller> getAllConseillers() {
        return gestionnairePersonne.getAllConseillers();
    }
    
    public List<Administrateur> getAllAdministrateurs() {
        return gestionnairePersonne.getAllAdministrateurs();
    }
    
    // Getter & setter
    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    
   //
    
    public String actionStringCeerClient(String url) {
        System.out.println("## Création d'un client");
    
        List<Conseiller> list = gestionnairePersonne.getAllConseillers();
        gestionnairePersonne.creerUnClient(nom, prenom, adresse, list.get(0));
        reset();
        return url + "?faces-redirect=true";
    }
    
    public String actionStringCeerConseiller(String url) {
        System.out.println("## Création d'un conseiller");
   
        gestionnairePersonne.creerUnConseiller(nom, prenom, adresse);
        reset();
        return url + "?faces-redirect=true";
    }
    
    public String actionStringCeerAdministrateur(String url) {
        System.out.println("## Création d'un administrateur");
   
        gestionnairePersonne.creerUnAdministrateur(nom, prenom, adresse);
        reset();
        return url + "?faces-redirect=true";
    }
    
    public String actionStringSupprimerClient(Long id, String url) {
        gestionnairePersonne.supprimerClient(id);
        return url + "?faces-redirect=true";
    }
    
    public String actionStringSupprimerConseiller(Long id, String url) {
        gestionnairePersonne.supprimerConseiller(id);
        return url + "?faces-redirect=true";
    }
    
    public String actionStringSupprimerAdministrateur(Long id, String url) {
        gestionnairePersonne.supprimerAdministrateur(id);
        return url + "?faces-redirect=true";
    }
    
    // Others
    private void reset() {
        nom = null;
        prenom = null;
        adresse = null;
    }
}

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/comptebancaire/creer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../templates/template_default.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="top">
        Céer un compte bancaire
    </ui:define>

    <ui:define name="content">
        <f:view>
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                Avant de créer un compte bancaire, vous devez créer un client puis le sélectionner ci-dessous.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <h:form class="container-fluid mb-3">
                <div class="form-row">
                    <div class="col">
                        <h:outputLabel value="Sélectionner un client :" for="client" />
                        <h:selectOneMenu
                            class="form-control"
                            id="client"
                            value = "#{compteBancaireMBean.clientId}">
                            <f:selectItems
                                value="#{personneMBean.allClients}" 
                                var="client"
                                itemLabel="#{client.nom} #{client.prenom}" 
                                itemValue="#{client.id}" />
                        </h:selectOneMenu>
                    </div>
                    <div class="col">
                        <h:outputLabel value="Type de compte :" for="type" />
                        <h:selectOneMenu
                            class="form-control"
                            id="type"
                            value = "#{compteBancaireMBean.type}">
                            <f:selectItems
                                value="#{compteBancaireMBean.types}" 
                                var="type"
                                itemLabel="#{type}" 
                                itemValue="#{type}" />
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="form-row mt-2">
                    <div class="col-6">
                        <h:outputLabel value="Dépôt initial à l'ouverture de compte :" for="montant" />
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="inputGroupPrepend">€</span>
                            </div>
                            <h:inputText 
                                id="montant"
                                class="form-control"
                                value="#{compteBancaireMBean.montant}"/>
                        </div>
                    </div>
                </div>
                <button type="button" class="btn btn-primary btn-sm mt-3" data-toggle="modal" data-target="#creer-compte-bancaire">
                    Créer le compte
                </button>
                <div class="modal fade" id="creer-compte-bancaire" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalCenterTitle">Opération de dépôt</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p class="h3">Voulez-vous vraiment créer un compte ${compteBancaireMBean.type} pour #{compteBancaireMBean.client.nom} #{compteBancaireMBean.client.prenom} </p>
                            </div>
                            <div class="modal-footer">
                                <button 
                                    type="button" 
                                    class="btn btn-secondary" 
                                    data-dismiss="modal">
                                    Non
                                </button>
                                <h:commandButton
                                    class="btn btn-primary" 
                                    value="Oui" 
                                    action="#{compteBancaireMBean.actionStringCreer('/faces/index')}"></h:commandButton>
                            </div>
                        </div>
                    </div>
                </div>
            </h:form>
            <div class="alert alert-secondary alert-dismissible fade show" role="alert">
                Le client aura par défaut comme conseiller celui qui lui crée son compte bancaire.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </f:view>
    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/comptebancaire/details.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../templates/template_default.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="top">
        Détails du compte
    </ui:define>

    <ui:define name="content">
        <p>Nom: <h:outputText value="#{compteBancaireMBean.nom}"/></p>
        <p>Solde: <h:outputText value="#{compteBancaireMBean.solde} €"/></p>
    </ui:define>

</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/comptebancaire/liste.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="./../templates/template_default.xhtml">

    <ui:define name="top">
       Comptes bancaires
    </ui:define>

    <ui:define name="content">
        <ui:repeat value="#{compteBancaireMBean.allComptes}" var="item">
            <div class="d-flex flex-column border rounded mb-3 bg-light container-fluid">
                <main class="row p-2">
                    <div class="col">
                        <p class="mb-0 font-weight-bold"><h:outputText value="#{item.nom}"/></p>
                        <ui:repeat value="#{item.clients}" var="client">
                            <p class="mb-0 text-capitalize"><h:outputText value="#{client.nom} #{client.prenom}"/></p>
                        </ui:repeat>
                    </div>
                    <div class="col text-right text-monospace h2">
                        <h:outputText value="#{item.solde} €"/>
                    </div>
                </main>
                <footer class="border-top p-2 row">
                    <h:form class="nav">
                        <div class="nav-item">
                            <h:commandButton 
                                class="nav-link text-primary border-0 bg-light" 
                                value="Historique des opérations" 
                                action="#{compteBancaireMBean.actionStringConsulter(item.compteBancaireId, '/faces/operation/historique')}" />
                        </div>
                        <div class="nav-item">
                            <a class="nav-link text-danger" data-toggle="modal" data-target="#supprimer-compte-bancaire-#{item.compteBancaireId}" href="#">
                                Supprimer
                            </a>
                            <div class="modal fade" id="supprimer-compte-bancaire-#{item.compteBancaireId}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Confirmation</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            Voulez-vous vraiment supprimer ce compte
                                        </div>
                                        <div class="modal-footer">
                                            <button 
                                                type="button" 
                                                class="btn btn-secondary btn-sm" 
                                                data-dismiss="modal">
                                                Non
                                            </button>
                                            <h:commandButton 
                                                class="btn btn-danger btn-sm" 
                                                value="Oui" 
                                                action="#{compteBancaireMBean.actionStringSupprimer(item.compteBancaireId, '/faces/comptebancaire/liste')}" />
                                        </div>
                                    </div>
                                </div>
                            </div>                            
                        </div>
                    </h:form>
                </footer>
            </div>
        </ui:repeat>
    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/comptebancaire/liste_bak.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="./../templates/template_default.xhtml">

    <ui:define name="top">
        liste des comptes bancaires
    </ui:define>

    <ui:define name="content">
        <f:view>
            <p:dataTable value="#{compteBancaireMBean.allComptes}" var="item">
                <p:column headerText="Nom">
                    <h:outputText value="#{item.nom}"/>
                </p:column>
                <p:column headerText="Solde">
                    <h:outputText value="#{item.solde} €"/>
                </p:column>
                <p:column headerText="Actions">
                    <h:form>
                        <div class="form-row">
                            <div class="col-auto">
                                <h:commandButton 
                                    class="btn btn-primary btn-sm" 
                                    value="Consulter" 
                                    action="#{compteBancaireMBean.actionStringConsulter(item.compteBancaireId, '/faces/comptebancaire/details')}" />
                            </div>
                            <div class="col-auto">
                                <h:commandButton 
                                    class="btn btn-secondary btn-sm" 
                                    value="Faire un dépot" 
                                    action="/faces/operation/depot"/>
                            </div>
                            <div class="col-auto">
                                <h:commandButton 
                                    class="btn btn-secondary btn-sm" 
                                    value="Faire un retrait" 
                                    action="/faces/operation/retrait"/>
                            </div>
                            <div class="col-auto">
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#supprimer-compte-bancaire">
                                    Supprimer
                                </button>
                                <div class="modal fade" id="supprimer-compte-bancaire" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalCenterTitle">Confirmation</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Voulez-vous vraiment supprimer ce compte
                                            </div>
                                            <div class="modal-footer">
                                                <button 
                                                    type="button" 
                                                    class="btn btn-secondary btn-sm" 
                                                    data-dismiss="modal">
                                                    Non
                                                </button>
                                                <h:commandButton 
                                                    class="btn btn-danger btn-sm" 
                                                    value="Oui" 
                                                    action="#{compteBancaireMBean.actionStringSupprimer(item.compteBancaireId, '/faces/comptebancaire/liste')}" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </h:form>
                </p:column>
            </p:dataTable>
        </f:view>
    </ui:define>
</ui:composition>