TP3BanqueAdamEme/TP3BanqueAdamEme-war/src/java/managed/PersonneMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managed;

import entity.Administrateur;
import entity.Client;
import entity.Conseiller;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import session.GestionnairePersonne;

/**
 *
 * @author issoufiadam
 */
@Named(value = "personneMBean")
@SessionScoped
public class PersonneMBean implements Serializable {

    @EJB
    private GestionnairePersonne gestionnairePersonne;
    
    String nom;
    String prenom;
    String adresse;
    Conseiller conseiller;
    
    /**
     * Creates a new instance of PersonneMBean
     */
    public PersonneMBean() {
    }
    
    //
    public List<Client> getAllClients() {
        return gestionnairePersonne.getAllClients();
    }
    
    public List<Conseiller> getAllConseillers() {
        return gestionnairePersonne.getAllConseillers();
    }
    
    public List<Administrateur> getAllAdministrateurs() {
        return gestionnairePersonne.getAllAdministrateurs();
    }
    
    // Getter & setter
    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    
   //
    
    public String actionStringCeerClient(String url) {
        System.out.println("## Création d'un client");
    
        List<Conseiller> list = gestionnairePersonne.getAllConseillers();
        gestionnairePersonne.creerUnClient(nom, prenom, adresse, list.get(0));
        reset();
        return url + "?faces-redirect=true";
    }
    
    public String actionStringCeerConseiller(String url) {
        System.out.println("## Création d'un conseiller");
   
        gestionnairePersonne.creerUnConseiller(nom, prenom, adresse);
        reset();
        return url + "?faces-redirect=true";
    }
    
    public String actionStringCeerAdministrateur(String url) {
        System.out.println("## Création d'un administrateur");
   
        gestionnairePersonne.creerUnAdministrateur(nom, prenom, adresse);
        reset();
        return url + "?faces-redirect=true";
    }
    
    public String actionStringSupprimerClient(Long id, String url) {
        gestionnairePersonne.supprimerClient(id);
        return url + "?faces-redirect=true";
    }
    
    public String actionStringSupprimerConseiller(Long id, String url) {
        gestionnairePersonne.supprimerConseiller(id);
        return url + "?faces-redirect=true";
    }
    
    public String actionStringSupprimerAdministrateur(Long id, String url) {
        gestionnairePersonne.supprimerAdministrateur(id);
        return url + "?faces-redirect=true";
    }
    
    // Others
    private void reset() {
        nom = null;
        prenom = null;
        adresse = null;
    }
}

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/personne/administrateurCreate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="./../templates/template_default.xhtml">

    <ui:define name="top">
       Créer un administrateur
    </ui:define>

    <ui:define name="content">
        <f:view>
            <h:form class="container-fluid">                 
                <div class="row">
                    <div class="col">
                    <h:outputLabel value="Nom" for="nom" />
                    <h:inputText class="form-control" id="nom" value="#{personneMBean.nom}" title="Nom" />
                    </div>
                    <div class="col">
                    <h:outputLabel value="Prénom" for="prenom" />
                    <h:inputText class="form-control" id="prenom" value="#{personneMBean.prenom}" title="Prénom" />
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                    <h:outputLabel value="Adresse" for="adresse" />
                    <h:inputText class="form-control" id="adresse" value="#{personneMBean.adresse}" title="Adresse" />
                    </div>
                </div>
                <h:commandButton id="update" class="btn btn-primary mt-3" value="Créer" action="#{personneMBean.actionStringCeerAdministrateur('/faces/index')}"/>
            </h:form>
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                Un identifiant et un mot de passe seront généré automatiquement après la création du compte 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </f:view>
    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/personne/administrateurs.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="./../templates/template_default.xhtml">

    <ui:define name="top">
       Administrateurs
    </ui:define>

    <ui:define name="content">
        <ui:repeat value="#{personneMBean.allAdministrateurs}" var="administrateur">
            <div class="d-flex flex-column border rounded mb-3 bg-light container-fluid">
                <main class="row p-2">
                    <div class="col">
                        <p class="mb-0 font-weight-bold text-capitalize"><h:outputText value="#{administrateur.nom} #{administrateur.prenom}"/></p>
                        <p class="mb-0"><h:outputText value="#{administrateur.adresse}"/></p>
                    </div>
                </main>
                <footer class="row border-top p-2">
                    <h:form class="nav">
                        <div class="nav-item">
                            <a class="nav-link" href="#">Modifier</a>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link text-danger" data-toggle="modal" data-target="#supprimer-administrateur-#{administrateur.id}" href="#">
                                Supprimer
                            </a>
                            <div class="modal fade" id="supprimer-administrateur-#{administrateur.id}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Confirmation</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            Voulez-vous vraiment supprimer l'administrateur #{administrateur.nom} #{administrateur.prenom}
                                        </div>
                                        <div class="modal-footer">
                                            <button 
                                                type="button" 
                                                class="btn btn-secondary btn-sm" 
                                                data-dismiss="modal">
                                                Non
                                            </button>
                                            <h:commandButton 
                                                class="btn btn-danger btn-sm" 
                                                value="Oui" 
                                                action="#{personneMBean.actionStringSupprimerAdministrateur(administrateur.id, '/faces/personne/administrateurs')}" />
                                        </div>
                                    </div>
                                </div>
                            </div>                            
                        </div>
                    </h:form>
                </footer>
            </div>
        </ui:repeat>
    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/personne/clientCreate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="./../templates/template_default.xhtml">

    <ui:define name="top">
        Créer un cllient
    </ui:define>

    <ui:define name="content">
        <f:view>
            <h:form class="container-fluid">                 
                <div class="row">
                    <div class="col">
                    <h:outputLabel value="Nom" for="nom" />
                    <h:inputText class="form-control" id="nom" value="#{personneMBean.nom}" title="Nom" />
                    </div>
                    <div class="col">
                    <h:outputLabel value="Prénom" for="prenom" />
                    <h:inputText class="form-control" id="prenom" value="#{personneMBean.prenom}" title="Prénom" />
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                    <h:outputLabel value="Adresse" for="adresse" />
                    <h:inputText class="form-control" id="adresse" value="#{personneMBean.adresse}" title="Adresse" />
                    </div>
                </div>
                <h:commandButton id="update" class="mt-3 btn btn-primary" value="Créer" action="#{personneMBean.actionStringCeerClient('/faces/index')}"/>
            </h:form>
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                Un identifiant et un mot de passe seront généré automatiquement après la création du compte 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </f:view>
    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/personne/clients.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="./../templates/template_default.xhtml">

    <ui:define name="top">
       Clients
    </ui:define>

    <ui:define name="content">
        <ui:repeat value="#{personneMBean.allClients}" var="client">
            <div class="d-flex flex-column border rounded mb-3 bg-light container-fluid">
                <main class="row p-2">
                    <div class="col">
                        <p class="mb-0 font-weight-bold text-capitalize"><h:outputText value="#{client.nom} #{client.prenom}"/></p>
                        <p class="mb-0"><h:outputText value="#{client.adresse}"/></p>
                    </div>
                </main>
                <footer class="row border-top p-2">
                    <h:form class="nav">
                        <div class="nav-item">
                            <a class="nav-link" href="#">Modifier</a>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link text-danger" data-toggle="modal" data-target="#supprimer-client-#{client.id}" href="#">
                                Supprimer
                            </a>
                            <div class="modal fade" id="supprimer-client-#{client.id}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Confirmation</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            Voulez-vous vraiment supprimer le client #{client.nom} #{client.prenom}
                                        </div>
                                        <div class="modal-footer">
                                            <button 
                                                type="button" 
                                                class="btn btn-secondary btn-sm" 
                                                data-dismiss="modal">
                                                Non
                                            </button>
                                            <h:commandButton 
                                                class="btn btn-danger btn-sm" 
                                                value="Oui" 
                                                action="#{personneMBean.actionStringSupprimerClient(client.id, '/faces/personne/clients')}" />
                                        </div>
                                    </div>
                                </div>
                            </div>                            
                        </div>
                    </h:form>
                </footer>
            </div>
        </ui:repeat>
    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/personne/conseillerCreate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="./../templates/template_default.xhtml">

    <ui:define name="top">
       Créer un conseiller
    </ui:define>

    <ui:define name="content">
        <f:view>
            <h:form class="container-fluid">                 
                <div class="row">
                    <div class="col">
                    <h:outputLabel value="Nom" for="nom" />
                    <h:inputText class="form-control" id="nom" value="#{personneMBean.nom}" title="Nom" />
                    </div>
                    <div class="col">
                    <h:outputLabel value="Prénom" for="prenom" />
                    <h:inputText class="form-control" id="prenom" value="#{personneMBean.prenom}" title="Prénom" />
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                    <h:outputLabel value="Adresse" for="adresse" />
                    <h:inputText class="form-control" id="adresse" value="#{personneMBean.adresse}" title="Adresse" />
                    </div>
                </div>
                <h:commandButton id="update" class="mt-3 btn btn-primary" value="Créer" action="#{personneMBean.actionStringCeerConseiller('/faces/index')}"/>
            </h:form>
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                Un identifiant et un mot de passe seront généré automatiquement après la création du compte 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </f:view>
    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/personne/conseillers.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="./../templates/template_default.xhtml">

    <ui:define name="top">
       Conseillers
    </ui:define>

    <ui:define name="content">
        <ui:repeat value="#{personneMBean.allConseillers}" var="conseiller">
            <div class="d-flex flex-column border rounded mb-3 bg-light container-fluid">
                <main class="row p-2">
                    <div class="col">
                        <p class="mb-0 font-weight-bold text-capitalize"><h:outputText value="#{conseiller.nom} #{conseiller.prenom}"/></p>
                        <p class="mb-0"><h:outputText value="#{conseiller.adresse}"/></p>
                    </div>
                </main>
                <footer class="row border-top p-2">
                    <h:form class="nav">
                        <div class="nav-item">
                            <a class="nav-link" href="#">Modifier</a>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link text-danger" data-toggle="modal" data-target="#supprimer-conseiller-#{conseiller.id}" href="#">
                                Supprimer
                            </a>
                            <div class="modal fade" id="supprimer-conseiller-#{conseiller.id}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Confirmation</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            Voulez-vous vraiment supprimer le conseiller #{conseiller.nom} #{conseiller.prenom}
                                        </div>
                                        <div class="modal-footer">
                                            <button 
                                                type="button" 
                                                class="btn btn-secondary btn-sm" 
                                                data-dismiss="modal">
                                                Non
                                            </button>
                                            <h:commandButton 
                                                class="btn btn-danger btn-sm" 
                                                value="Oui" 
                                                action="#{personneMBean.actionStringSupprimerConseiller(conseiller.id, '/faces/personne/conseillers')}" />
                                        </div>
                                    </div>
                                </div>
                            </div>                            
                        </div>
                    </h:form>
                </footer>
            </div>
        </ui:repeat>
    </ui:define>
</ui:composition>