TP3BanqueAdamEme/TP3BanqueAdamEme-war/src/java/managed/CompteBancaireMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managed;

import entity.Client;
import entity.CompteBancaire;
import entity.Operation;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import session.GestionnaireDeCompteBancaire;
import session.GestionnairePersonne;

/**
 *
 * @author issoufiadam
 */
@Named(value = "compteBancaireMBean")
@SessionScoped
public class CompteBancaireMBean implements Serializable{
   
    @EJB
    private GestionnaireDeCompteBancaire gestionnaireDeCompteBancaire;
    @EJB
    private GestionnairePersonne gestionnairePersonne;
    
    private List<CompteBancaire> comptes = new ArrayList<CompteBancaire>();
    private CompteBancaire compteCourant = null;
    
    // attribut utilisé lors de la création de compte
    private String type;
    private Client client;
    private Long clientId;
    private int montant = 0;
    
    /**
     * Creates a new instance of ListCompteBancaireMBean
     */
    public CompteBancaireMBean() {
        // gestionnaireDeCompteBancaire.creerComptesTest();
    }
    
    public void creerCompteBancaireTest() {
        gestionnaireDeCompteBancaire.creerComptesTest();
    } 
    
    public List<CompteBancaire> getAllComptes() {
        return gestionnaireDeCompteBancaire.getAllComptes();
    }
    
    public Collection<Operation> getAllOperations() {
        if (compteCourant == null) return null;
        return compteCourant.getOperations();
    }
    
    public List<String> getTypes() {
        return gestionnaireDeCompteBancaire.getTypes();
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(String clientId) {
        this.client = gestionnairePersonne.getClient(Long.parseLong(clientId, 10));
    }

    public int getMontant() {
        return montant;
    }

    public void setMontant(int montant) {
        this.montant = montant;
    }
    
    public void creerCompte(CompteBancaire c) {
        gestionnaireDeCompteBancaire.creerCompte(c);
    }
    
    public CompteBancaire getCompte(Long compteBancaireId) {
        return gestionnaireDeCompteBancaire.getCompte(compteBancaireId);
    }
    
    public CompteBancaire getCompteCourant() {
        return compteCourant;
    }
    
    public String getNom() {
        return (compteCourant == null) ? "Undefined" : compteCourant.getNom();
    }
    
    public String getSolde() {
        return (compteCourant == null) ? "Undefined" : "" + compteCourant.getSolde();
    }
    
    public void setCompteCourant(Long compteBancaireId) {
        System.out.println("Compte courant : " + compteBancaireId);
        compteCourant = gestionnaireDeCompteBancaire.getCompte(compteBancaireId);
    }

    public Long getClientId() {
        return clientId;
    }

    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }
    

    // Les actions string
    public String actionStringCreer(String url) {
        System.out.println("managed.CompteBancaireMBean.actionStringCreer()");
        if (clientId == null || type == null) return url + "?faces-redirect=true";
        this.client = gestionnairePersonne.getClient(clientId);
        gestionnaireDeCompteBancaire.creerCompte(type, montant, client);
        reset();
        return url + "?faces-redirect=true";
    }
    
    public String actionStringSupprimer(Long compteBancaireId, String url) {
        gestionnaireDeCompteBancaire.supprimer(compteBancaireId);
        return url + "?faces-redirect=true";
    }
    
    public String actionStringConsulter(Long compteBancaireId, String url) {
        compteCourant = gestionnaireDeCompteBancaire.getCompte(compteBancaireId);
        return url + "?faces-redirect=true";
    }
    
    // Other
    public void reset() {
        clientId = null;
        type = null;
        montant = 0;
    }
}

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/operation/depot.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../templates/template_default.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="top">
        Effectuer dépôt
    </ui:define>

    <ui:define name="content">
        <h:form class="needs-validation">
            <div class="form-row">
                <div class="col-4">
                    <label for="compteCredite">Compte à créditer : </label>
                    <h:selectOneListbox
                        class="form-control"
                        id="compteCredite"
                        size="1"
                        value = "#{operationsMBean.compteCredite}">
                        <f:selectItems
                            value="#{compteBancaireMBean.allComptes}" 
                            var="cb"
                            itemLabel="#{cb.clients[0].nom} #{cb.clients[0].prenom} / #{cb.nom} / #{cb.solde}€" 
                            itemValue="#{cb.compteBancaireId}" />
                    </h:selectOneListbox>
                </div>
            </div>
            <div class="form-row mt-2">
                <div class="col-4">
                    <label for="montant">Entrez un montant à déposer :</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupPrepend">€</span>
                        </div>
                        <h:inputText 
                            id="montant"
                            class="form-control"
                            value="#{operationsMBean.montant}"/>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-primary btn-sm mt-3" data-toggle="modal" data-target="#transfert-compte-bancaire">
                Effectuer le retrait
            </button>
            <div class="modal fade" id="transfert-compte-bancaire" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Opération de dépôt</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                        <div class="modal-body">
                            <p class="h3">Voulez-vous vraiment effectuer le dépôt ?</p>
                        </div>
                        <div class="modal-footer">
                            <button 
                                type="button" 
                                class="btn btn-secondary" 
                                data-dismiss="modal">
                                Non
                            </button>
                            <h:commandButton 
                                class="btn btn-primary" 
                                value="Oui" 
                                action="#{operationsMBean.actionStringDeposer('/faces/index')}" />
                        </div>
                    </div>
                </div>
            </div>
        </h:form>  
    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/operation/historique.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../templates/template_default.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="top">
        Historique des opérations
    </ui:define>

    <ui:define name="content">
        <f:view>
            <h:form>
                <p:dataTable 
                    id="tab"
                    value="#{compteBancaireMBean.allOperations}" 
                    var="item"
                    paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {Exporters}"
                    paginator="true"
                    rows="10">
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Compte"/>
                        </f:facet>
                        <h:outputText value="#{item.compte}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Date"/>
                        </f:facet>
                        <h:outputText value="#{item.date}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Montant"/>
                        </f:facet>
                        <h:outputText value="#{item.montant}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Type"/>
                        </f:facet>
                        <h:outputText value="#{item.type}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="N° de transaction"/>
                        </f:facet>
                        <h:outputText value="#{item.id}"/>
                    </p:column>
                </p:dataTable>
                <div class="mt-3">
                    <h:commandLink>
                        <p:graphicImage name="/img/excel.png" width="24"/>
                        <p:dataExporter type="xls" target="tab" fileName="allOperations" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage name="/img/pdf.png" width="24"/>
                        <p:dataExporter type="pdf" target="tab" fileName="allOperations"/>
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage name="/img/csv.png" width="24"/>
                        <p:dataExporter type="csv" target="tab" fileName="allOperations" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage name="/img/xml.png" width="24"/>
                        <p:dataExporter type="xml" target="tab" fileName="allOperations" />
                    </h:commandLink>
                </div>
            </h:form>
        </f:view>

    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/operation/retrait.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../templates/template_default.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="top">
        Effectuer un retrait
    </ui:define>

    <ui:define name="content">
        <h:form class="needs-validation">
            <div class="form-row">
                <div class="col-4">
                    <label for="compteDebite">Compte à débiter : </label>
                    <h:selectOneListbox
                        class="form-control"
                        id="compteDebite"
                        size="1"
                        value = "#{operationsMBean.compteDebite}">
                        <f:selectItems
                            value="#{compteBancaireMBean.allComptes}" 
                            var="cb"
                            itemLabel="#{cb.clients[0].nom} #{cb.clients[0].prenom} / #{cb.nom} / #{cb.solde}€" 
                            itemValue="#{cb.compteBancaireId}" />
                    </h:selectOneListbox>
                </div>
            </div>
            <div class="form-row mt-2">
                <div class="col-4">
                    <label for="montant">Entrez un montant à retirer :</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupPrepend">€</span>
                        </div>
                        <h:inputText 
                            id="montant"
                            class="form-control"
                            value="#{operationsMBean.montant}"/>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-primary btn-sm mt-3" data-toggle="modal" data-target="#transfert-compte-bancaire">
                Effectuer le retrait
            </button>
            <div class="modal fade" id="transfert-compte-bancaire" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Opération de retrait</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p class="h3">Voulez-vous vraiment effectuer le retrait ?</p>
                        </div>
                        <div class="modal-footer">
                            <button 
                                type="button" 
                                class="btn btn-secondary" 
                                data-dismiss="modal">
                                Non
                            </button>
                            <h:commandButton 
                                class="btn btn-primary" 
                                value="Oui" 
                                action="#{operationsMBean.actionStringRetirer('/faces/index')}" />
                        </div>
                    </div>
                </div>
            </div>
        </h:form>  
    </ui:define>
</ui:composition>

TP3BanqueAdamEme/TP3BanqueAdamEme-war/web/operation/transfert.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../templates/template_default.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="top">
        Effectuer un transfert
    </ui:define>

    <ui:define name="content">
        <h:form class="needs-validation">
            <div class="form-row">
                <div class="col">
                    <label for="compteDebite">Compte à débiter : </label>
                    <h:selectOneMenu
                        class="form-control"
                        id="compteDebite"
                        value = "#{operationsMBean.compteDebite}">
                        <f:selectItems
                            value="#{compteBancaireMBean.allComptes}" 
                            var="cb"
                            itemLabel="#{cb.clients[0].nom} #{cb.clients[0].prenom} / #{cb.nom} / #{cb.solde}€" 
                            itemValue="#{cb.compteBancaireId}" />
                    </h:selectOneMenu>
                </div>
                <div class="col">
                    <label for="montant">Montant :</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupPrepend">€</span>
                        </div>
                        <h:inputText 
                            id="montant"
                            class="form-control"
                            value="#{operationsMBean.montant}"/>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-6">
                    <label for="compteCredite">Compte à créditer : </label>
                    <h:selectOneMenu
                        class="form-control"
                        id="compteCredite"
                        value = "#{operationsMBean.compteCredite}">
                        <f:selectItems
                            value="#{compteBancaireMBean.allComptes}" 
                            var="cb"
                            itemLabel="#{cb.clients[0].nom} #{cb.clients[0].prenom} / #{cb.nom} / #{cb.solde}€" 
                            itemValue="#{cb.compteBancaireId}" />
                    </h:selectOneMenu>
                </div>
            </div>
            <button type="button" class="btn btn-primary btn-sm mt-3" data-toggle="modal" data-target="#transfert-compte-bancaire">
                Effectuer le transfert
            </button>
            <div class="modal fade" id="transfert-compte-bancaire" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Opération de transfert</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p class="h3">Voulez-vous vraiment effectuer le transfert ?</p>
                        </div>
                        <div class="modal-footer">
                            <button 
                                type="button" 
                                class="btn btn-secondary" 
                                data-dismiss="modal">
                                Non
                            </button>
                            <h:commandButton 
                                class="btn btn-primary" 
                                value="Oui" 
                                action="#{operationsMBean.actionStringTransferer('/faces/comptebancaire/liste')}" />
                        </div>
                    </div>
                </div>
            </div>
        </h:form>  
    </ui:define>
</ui:composition>