TP1CustomerApplication/TP1CustomerApplication-war/src/java/managedbeans/CustomerDetailsMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbeans;

import entities.Customer;
import entities.DiscountCode;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.ConverterException;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import session.CustomerManager;
import session.DiscountCodeManager;

/**
 *
 * @author issoufiadam
 */
@Named(value = "customerDetailsMBean")
@ViewScoped
public class CustomerDetailsMBean implements Serializable {
    
    @EJB
    private CustomerManager customerManager;
    @EJB  
    private DiscountCodeManager discountCodeManager;  
    
    private int idCustomer;
    private Customer customer;
    /**
     * Creates a new instance of CustomerDetailsMBean
     */
    public CustomerDetailsMBean() {
    }


    public int getIdCustomer() {
      return idCustomer;
    }

    public void setIdCustomer(int idCustomer) {
      this.idCustomer = idCustomer;
    }

    /**
     * Renvoie les détails du client courant (celui dans l'attribut customer de
     * cette classe), qu'on appelle une propriété (property)
     */
    public Customer getDetails() {
      return customer;
    }

    /**
     * Action handler - met à jour la base de données en fonction du client passé
     * en paramètres, et renvoie vers la page qui affiche la liste des clients.
     */
    public String update() {
      System.out.println("###UPDATE###");
      customer = customerManager.update(customer);
      return "CustomerList";
    }

    /**
     * Action handler - renvoie vers la page qui affiche la liste des clients
     * @return 
     */
    public String list() {
      System.out.println("###LIST###");
      return "CustomerList";
    }

    public void loadCustomer() {
      this.customer = customerManager.getCustomer(idCustomer);
    }

    public Converter getDiscountCodeConverter() {  
        return discountCodeConverter;  
    }
    
    /** 
    * renvoie une liste de DiscountCode pour affichage dans le menu déroulant 
    * de la page des détails d'un client 
    * @return 
    */  
   public List<DiscountCode> getAllDiscountCodes() {  
       return discountCodeManager.getDiscountCodes();  
   } 

    private Converter discountCodeConverter = new Converter() {  

        @Override  
        public Object getAsObject(FacesContext context, UIComponent component, String value) {  
            char code = value.charAt(0);  
            DiscountCode dc = discountCodeManager.getDiscountCodeByDiscountCode(code);  
            return dc;  
       }  
        @Override  
        public String getAsString(FacesContext context, UIComponent component, Object value) {  
            DiscountCode dc = (DiscountCode) value;  
            return dc.getDiscountCode()+" : "+dc.getRate()+"%";   
        }  
    };
}

TP1CustomerApplication/TP1CustomerApplication-war/src/java/managedbeans/CustomerMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbeans;

import entities.Customer;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import session.CustomerManager;

/**
 *
 * @author issoufiadam
 */
@Named(value = "customerMBean")
@ViewScoped
public class CustomerMBean implements Serializable {

    @EJB
    private CustomerManager customerManager;
    
    private List<Customer> customers;

    /**
     * Creates a new instance of CustomerMBean
     */
    public CustomerMBean() {
    }
    
    /**
     * Renvoie la liste des clients pour affichage dans une DataTable
     * @return
     */
    public List<Customer>getCustomers() {
        if (this.customers == null) {
           this.customers = customerManager.getAllCustomers();
        }
        
        return this.customers;
    }

    /**
     * Action handler - appelé lorsque l'utilisateur sélectionne une ligne dans
     * la DataTable pour voir les détails
     */
    public String showDetails(int customerId) {
        return "CustomerDetails?idCustomer=" + customerId;    }
    
    
}

TP1CustomerApplication/TP1CustomerApplication-war/web/CustomerDetails.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <f:metadata>
        <f:viewParam name="idCustomer" value="#{customerDetailsMBean.idCustomer}"  
                     required="true"/>  
        <f:viewAction action="#{customerDetailsMBean.loadCustomer}"/>  
    </f:metadata>
    <h:head>
        <title>Détails d'un client</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="Create/Edit"/></h1>
                <h:panelGrid columns="2">
                    <h:outputLabel value="CustomerId:" for="customerId" />
                    <h:inputText id="customerId" value="#{customerDetailsMBean.details.customerId}" title="CustomerId" required="true" requiredMessage="The CustomerId field is required."/>
                    <h:outputLabel value="Name:" for="name" />
                    <h:inputText id="name" value="#{customerDetailsMBean.details.name}" title="Name" />
                    <h:outputLabel value="Addressline1:" for="addressline1" />
                    <h:inputText id="addressline1" value="#{customerDetailsMBean.details.addressline1}" title="Addressline1" />
                    <h:outputLabel value="Addressline2:" for="addressline2" />
                    <h:inputText id="addressline2" value="#{customerDetailsMBean.details.addressline2}" title="Addressline2" />
                    <h:outputLabel value="City:" for="city" />
                    <h:inputText id="city" value="#{customerDetailsMBean.details.city}" title="City" />
                    <h:outputLabel value="State:" for="state" />
                    <h:inputText id="state" value="#{customerDetailsMBean.details.state}" title="State" />
                    <h:outputLabel value="Phone:" for="phone" />
                    <h:inputText id="phone" value="#{customerDetailsMBean.details.phone}" title="Phone" />
                    <h:outputLabel value="Fax:" for="fax" />
                    <h:inputText id="fax" value="#{customerDetailsMBean.details.fax}" title="Fax" />
                    <h:outputLabel value="Email:" for="email" />
                    <h:inputText id="email" value="#{customerDetailsMBean.details.email}" title="Email" />
                    <h:outputLabel value="CreditLimit:" for="creditLimit" />
                    <h:inputText id="creditLimit" value="#{customerDetailsMBean.details.creditLimit}" title="CreditLimit" />
                    <h:outputLabel value="DiscountCode:" for="discountCode" />
                    <h:selectOneMenu id="discountCode" value="#{customerDetailsMBean.details.discountCode}"   
                                    title="DiscountCode" required="true" requiredMessage="The DiscountCode field is required."  
                                    converter="#{customerDetailsMBean.discountCodeConverter}">   
                        <f:selectItems value="#{customerDetailsMBean.allDiscountCodes}"  
                                           var="item"   
                                           itemLabel="#{item.discountCode} : #{item.rate} %" itemValue="#{item}" />  
                    </h:selectOneMenu>  
                    <h:outputLabel value="Zip:" for="zip" />
                    <h:selectOneMenu id="zip" value="#{customerDetailsMBean.details.zip}" title="Zip" required="true" requiredMessage="The Zip field is required.">
                        <!-- TODO: update below reference to list of available items-->
                        <f:selectItems value="#{fixme}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandButton id="back" value="Back" action="#{customerDetailsMBean.list}"/>  
                <h:commandButton id="update" value="Update" action="#{customerDetailsMBean.update}"/>  
            </h:form>
        </f:view>

    </h:body>
</html>

TP1CustomerApplication/TP1CustomerApplication-war/web/CustomerList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Liste des clients</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="Liste des clients"/></h1>
                <p:dataTable 
                    value="#{customerMBean.customers}" 
                    var="item"
                    paginator="true"
                    rows="10">
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="CustomerId"/>
                        </f:facet>
                        <h:link 
                            outcome="#{customerMBean.showDetails(item.customerId)}" 
                            value="#{item.customerId}"/>
                    </p:column>
                    <p:column sortBy="#{item.name}">
                        <f:facet name="header">
                            <h:outputText value="Name"/>
                        </f:facet>
                        <h:outputText value="#{item.name}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Addressline1"/>
                        </f:facet>
                        <h:outputText value="#{item.addressline1}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Addressline2"/>
                        </f:facet>
                        <h:outputText value="#{item.addressline2}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="City"/>
                        </f:facet>
                        <h:outputText value="#{item.city}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="State"/>
                        </f:facet>
                        <h:outputText value="#{item.state}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Phone"/>
                        </f:facet>
                        <h:outputText value="#{item.phone}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Fax"/>
                        </f:facet>
                        <h:outputText value="#{item.fax}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Email"/>
                        </f:facet>
                        <h:outputText value="#{item.email}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="CreditLimit"/>
                        </f:facet>
                        <h:outputText value="#{item.creditLimit}"/>
                    </p:column>
                    <p:column headerText="DiscountCode"  
                            sortBy="#{item.discountCode.discountCode}"  
                            filterBy="#{item.discountCode.rate}%"  
                            filterMatchMode="contains">  
                      <h:outputText value="#{item.discountCode}" converter="#{customerDetailsMBean.discountCodeConverter}"/>  
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Zip"/>
                        </f:facet>
                        <h:outputText value="#{item.zip.zipCode}"/>
                    </p:column>

                </p:dataTable>
            </h:form>
        </f:view>

    </h:body>
</html>